# Generated by Django 3.1.7 on 2021-04-22 21:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AS', 'American Samoa'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('AA', 'Armed Forces Americas'), ('AE', 'Armed Forces Europe'), ('AP', 'Armed Forces Pacific'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('GU', 'Guam'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('MP', 'Northern Mariana Islands'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('PR', 'Puerto Rico'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VI', 'Virgin Islands'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2)),
                ('description', models.CharField(max_length=1000)),
                ('program_link', models.URLField(max_length=500)),
                ('program_image', models.ImageField(blank=True, null=True, upload_to=core.models.get_image_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Quote',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='contact_phone_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='overall_tags',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='street',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='zipcode',
        ),
        migrations.RenameModel(
            old_name='Arching_Tag',
            new_name='Technology_Tag',
        ),
        migrations.AddField(
            model_name='program',
            name='affiliations',
            field=models.ManyToManyField(to='core.Organization'),
        ),
        migrations.AddField(
            model_name='program',
            name='contact',
            field=models.ManyToManyField(to='core.Contact'),
        ),
        migrations.AddField(
            model_name='program',
            name='focus',
            field=models.ManyToManyField(to='core.Tag'),
        ),
        migrations.AddField(
            model_name='program',
            name='technology_tags',
            field=models.ManyToManyField(to='core.Technology_Tag'),
        ),
        migrations.AddField(
            model_name='award',
            name='program',
            field=models.ManyToManyField(to='core.Program'),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact',
            field=models.ManyToManyField(to='core.Contact'),
        ),
    ]
