# Generated by Django 3.1.7 on 2021-04-22 21:35

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_organization_affiliations'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='dates',
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
