# Generated by Django 3.1.7 on 2021-04-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210422_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_type',
            name='color',
        ),
        migrations.AddField(
            model_name='tag_type',
            name='option_type',
            field=models.CharField(default='RADIO', max_length=5),
            preserve_default=False,
        ),
    ]
